### ISSUE TITLE
✍️ Contribution period: Masroor Hussain Shah 

### ISSUE THREAD

**Issue by masroor07** [ersilia-os/ersilia#611]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [X] Select a model from the suggested list
- [X] Install the model in your system
- [X] Run predictions for the EML
- [X] Compare results with the Ersilia Model Hub implementation!

### Week 3 - Propose new models

- [X] Suggest a new model an document it (1)
- [X] Suggest a new model an document it (2)
- [X] Suggest a new model an document it (3)

### Week 4 - Prepare your final application

- [X] Submit the final application in the Outreachy website

**Comment by masroor07** [comment]
I am trying to setup Ersilia on my system using WSl 2 (Ubuntu). I have set up the environment, but trying to install Ersilia python package using "pip install -e .", my system crashes.

**Comment by masroor07** [comment]
The command finally worked but cannot access ersilia from the command line. It throws the following: 

![er issue](https://user-images.githubusercontent.com/76279044/223353032-e64284eb-1112-4f79-82db-4137d23479a5.JPG)

**Comment by masroor07** [comment]
I tried to install ersilia on my system using WSl 2 (Ubuntu). I followed the commands but it did not works.

The total error message shows as below. I'm sorry to bother you, but I'd appreciate your help. Thank you for your hard works.
```
Obtaining file:///home/masroorshah/ersilia
  Preparing metadata (setup.py) ... done
Collecting bentoml@ git+https://github.com/ersilia-os/bentoml-ersilia.git
  Cloning https://github.com/ersilia-os/bentoml-ersilia.git to /tmp/pip-install-k2y0wew3/bentoml_1a165b7ec33547ffb70557169b405a9f
  Running command git clone --filter=blob:none --quiet https://github.com/ersilia-os/bentoml-ersilia.git /tmp/pip-install-k2y0wew3/bentoml_1a165b7ec33547ffb70557169b405a9f
  Resolved https://github.com/ersilia-os/bentoml-ersilia.git to commit a0f0040a1198e8f1704f0395e5d9ce328aaecf71
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f02d10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11810>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11ad0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11e10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by pauline-banye** [comment]
> I tried to install ersilia on my system using WSl 2 (Ubuntu). I followed the commands but it did not works.
> 
> The total error message shows as below. I'm sorry to bother you, but I'd appreciate your help. Thank you for your hard works.
> 
> ```
> Obtaining file:///home/masroorshah/ersilia
>   Preparing metadata (setup.py) ... done
> Collecting bentoml@ git+https://github.com/ersilia-os/bentoml-ersilia.git
>   Cloning https://github.com/ersilia-os/bentoml-ersilia.git to /tmp/pip-install-k2y0wew3/bentoml_1a165b7ec33547ffb70557169b405a9f
>   Running command git clone --filter=blob:none --quiet https://github.com/ersilia-os/bentoml-ersilia.git /tmp/pip-install-k2y0wew3/bentoml_1a165b7ec33547ffb70557169b405a9f
>   Resolved https://github.com/ersilia-os/bentoml-ersilia.git to commit a0f0040a1198e8f1704f0395e5d9ce328aaecf71
>   Installing build dependencies ... error
>   error: subprocess-exited-with-error
> 
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [7 lines of output]
>       WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f02d10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
>       WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
>       WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11810>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
>       WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11ad0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
>       WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11e10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
>       ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
>       ERROR: No matching distribution found for setuptools>=40.8.0
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

Hi, could you check your internet connection and try again?

**Comment by masroor07** [comment]
> > I tried to install ersilia on my system using WSl 2 (Ubuntu). I followed the commands but it did not works.
> > The total error message shows as below. I'm sorry to bother you, but I'd appreciate your help. Thank you for your hard works.
> > ```
> > Obtaining file:///home/masroorshah/ersilia
> >   Preparing metadata (setup.py) ... done
> > Collecting bentoml@ git+https://github.com/ersilia-os/bentoml-ersilia.git
> >   Cloning https://github.com/ersilia-os/bentoml-ersilia.git to /tmp/pip-install-k2y0wew3/bentoml_1a165b7ec33547ffb70557169b405a9f
> >   Running command git clone --filter=blob:none --quiet https://github.com/ersilia-os/bentoml-ersilia.git /tmp/pip-install-k2y0wew3/bentoml_1a165b7ec33547ffb70557169b405a9f
> >   Resolved https://github.com/ersilia-os/bentoml-ersilia.git to commit a0f0040a1198e8f1704f0395e5d9ce328aaecf71
> >   Installing build dependencies ... error
> >   error: subprocess-exited-with-error
> > 
> >   × pip subprocess to install build dependencies did not run successfully.
> >   │ exit code: 1
> >   ╰─> [7 lines of output]
> >       WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f02d10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
> >       WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
> >       WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11810>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
> >       WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11ad0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
> >       WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2097f11e10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
> >       ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
> >       ERROR: No matching distribution found for setuptools>=40.8.0
> >       [end of output]
> > 
> >   note: This error originates from a subprocess, and is likely not a problem with pip.
> > error: subprocess-exited-with-error
> > 
> > × pip subprocess to install build dependencies did not run successfully.
> > │ exit code: 1
> > ╰─> See above for output.
> > 
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> > ```
> 
> Hi, could you check your internet connection and try again?

I just sorted this issue, but ain't able to fetch a model

**Comment by masroor07** [comment]
```
⬇️  Fetching model eos3b5e: molecular-weight
Checking setup: 0.934s                                                                                                              
Preparing model: 11.815153121948242s                                                                                                
Getting model: 1.909874439239502s                                                                                                   
Packing model: 37.34964108467102s                                                                                                   
Checking if model needs to be integrated to a tool: 0.0018198490142822266s                                                          
 62%|████████████████████████████████████████████████████████████▋                                    | 5/8 [00:52<00:53, 17.69s/it]Traceback (most recent call last):
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/masroorshah/miniconda3/envs/ersilia/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/masroorshah/ersilia/ersilia/cli/commands/fetch.py", line 43, in fetch
    _fetch(mf, model_id)
  File "/home/masroorshah/ersilia/ersilia/cli/commands/fetch.py", line 12, in _fetch
    mf.fetch(model_id)
  File "/home/masroorshah/ersilia/ersilia/hub/fetch/fetch.py", line 151, in fetch
    self._content()
  File "/home/masroorshah/ersilia/ersilia/hub/fetch/fetch.py", line 85, in _content
    cg = CardGetter(self.model_id, self.config_json)
  File "/home/masroorshah/ersilia/ersilia/hub/fetch/actions/content.py", line 14, in __init__
    self.mc = ModelCard(config_json=config_json)
  File "/home/masroorshah/ersilia/ersilia/hub/content/card.py", line 653, in __init__
    self.ac = AirtableCard(config_json=config_json)
  File "/home/masroorshah/ersilia/ersilia/hub/content/card.py", line 591, in __init__
    AirtableInterface.__init__(self, config_json=config_json)
  File "/home/masroorshah/ersilia/ersilia/db/hubdata/interfaces.py", line 13, in __init__
    self.api_key = self._get_read_only_airtable_api_key()
  File "/home/masroorshah/ersilia/ersilia/db/hubdata/interfaces.py", line 24, in _get_read_only_airtable_api_key
    r = requests.get(url)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/masroorshah/miniconda3/envs/ersilia/lib/python3.7/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
 62%|████████████████████████████████████████████████████████████▋                                    | 5/8 [00:53<00:32, 10.69s/it]
```

**Comment by masroor07** [comment]
I am not able to load fetch the model.
command:
` ersilia -v fetch eos3b5e`

Error message:
```
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io
 
```

**Comment by leoank** [comment]
Hey @masroor07, This still looks like a connection issue. `ersilia` downloads a lot of dependencies during model fetching. Your error shows a `Connection Reset`. Please try to find a good connection and retry. Let us know if the issue persist even after doing this.

**Comment by masroor07** [comment]
> Hey @masroor07, This still looks like a connection issue. `ersilia` downloads a lot of dependencies during model fetching. Your error shows a `Connection Reset`. Please try to find a good connection and retry. Let us know if the issue persist even after doing this.

Yeah, figured it out! Turns out it certainly was a connection error. I ran the command a couple of times before it finally fetched the model.
```
👍 Model eos3b5e fetched successfully!
(ersilia) masroorshah@DESKTOP-0P188GE:~/ersilia$ ersilia serve eos3b5e
🚀 Serving model eos3b5e: molecular-weight
```

 I was able to get the molecular weight of the molecules by running the following command:
`ersilia -v api calculate -i "CCCC"`
**Output:**
```
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "mw": 58.123999999999995
    }
}
```

**Comment by masroor07** [comment]
> Hi @masroor07 !
> 
> Great start, thanks for a good reporting of the issue! Normally, as @leoank and @pauline-banye (thanks both for your support) pointed out, every time you see a connection error somewhere its due to internet issues, not related to the code

Alright ma'am! thank you for the review

**Comment by masroor07** [comment]
**Motivation statement:**

I found about Outreachy and all the work it has been doing to support the people in diversity. Since then, I had been waiting for the opportunity to get to apply to Outreachy. After applying, I was so nervous, waiting for the initial Application's result to come out. And when it did, I straightaway started looking for organizations to contribute to. During the process, i came across Ersilia and all the work done by them to provide powerful data science tools to tackle various infectious in underdeveloped countries. 

It felt overwhelming, but interesting and fascinating to me that I will be contributing to something that can help people from under presented group. It excites that I will be getting to interact with people from around the globe and possibly make new friends while learning. 

I can also relate to the struggle that the infrastructure of Medical science industry faces in the underdeveloped areas and how Ersilia can help. Ersilia can expose the Medical industries in the underdeveloped countries to new possibilities and better diagnosis of patients. 

I have been into various Techstacks like DevOps, Web development and Data analyzation, and am currently a pursuing a Bachelors degree in the field of Computer Science. I have also been interested in AI/ML and have tried learning about it from various online resources.  I have worked on various data sets and performed analysis on them.

Ersilia seems like i am heading in the right direction to learn about data science, AI/ML and how I can be someone who can make a difference in the society and motivate many more people from the under-presented. It will also give me the right experience needed to learn more about AI/ML and expose me to Data science. I will try to maximize my data science learnings during the internship and keep working on Data science projects after the internship.

**Comment by ZakiaYahya** [comment]
> Hey @masroor07, This still looks like a connection issue. `ersilia` downloads a lot of dependencies during model fetching. Your error shows a `Connection Reset`. Please try to find a good connection and retry. Let us know if the issue persist even after doing this.

i'm getting the same issue, run fetch command multiple times but getting the same error. i have switched to different network as well but no gain. How you able to run it by just running iut multiple times?? i'm doing that since yesterday but it didn't worked

**Comment by masroor07** [comment]
> > Hey @masroor07, This still looks like a connection issue. `ersilia` downloads a lot of dependencies during model fetching. Your error shows a `Connection Reset`. Please try to find a good connection and retry. Let us know if the issue persist even after doing this.
> 
> i'm getting the same issue, run fetch command multiple times but getting the same error. i have switched to different network as well but no gain. How you able to run it by just running iut multiple times?? i'm doing that since yesterday but it didn't worked

Did you install all the dependencies alright? You can try connecting to a VPN and if you keep getting the same error again, just try after sometime. Hope that helps! In my case, it took me around 3-4 hours to set it up.

**Comment by ZakiaYahya** [comment]
> > > Hey @masroor07, This still looks like a connection issue. `ersilia` downloads a lot of dependencies during model fetching. Your error shows a `Connection Reset`. Please try to find a good connection and retry. Let us know if the issue persist even after doing this.
> > 
> > 
> > i'm getting the same issue, run fetch command multiple times but getting the same error. i have switched to different network as well but no gain. How you able to run it by just running iut multiple times?? i'm doing that since yesterday but it didn't worked
> 
> Did you install all the dependencies alright? You can try connecting to a VPN and if you keep getting the same error again, just try after sometime. Hope that helps! In my case, it took me around 3-4 hours to set it up.

Yes,  i have checked it by running ersilia --help and ersilia catalog commands and it runs successfully.  @masroor07 Thanks, i'm trying it by tracking some errors.

**Comment by masroor07** [comment]
> Hi @masroor07,
> 
> Please complete the initial outrachy application and we will be ready to continue with some more tasks!

Hello @GemmaTuron 
Should I use this issues link to record my first contribution for Ersilia on Outreachy? Will that complete my initial outreachy application?

**Comment by masroor07** [comment]
> Hi @masroor07,
> 
> Please complete the initial outrachy application and we will be ready to continue with some more tasks!

Hello @GemmaTuron,
 I just finished my initial Outreachy application and am ready to continue with more tasks.

Thank you

**Comment by masroor07** [comment]
> Hi @masroor07 please can you work on this: `https://github.com/ersilia-os/eos1bba/issues/4`
> 
> If the model is not working, try to figure out where is it failing

Alright Ma'am! On it

Thank you for the task

**Comment by GemmaTuron** [comment]
Just for context: This model has recently been incorporated by @karthikjetty , a Stanford intern at Ersilia. 
@karthikjetty please stay on top of this testing to make sure the model is working in different systems, and provide feedback when necessary.

Thanks for working together on this!

**Comment by masroor07** [comment]
> Just for context: This model has recently been incorporated by @karthikjetty , a Stanford intern at Ersilia. @karthikjetty please stay on top of this testing to make sure the model is working in different systems, and provide feedback when necessary.
> 
> Thanks for working together on this!

Sure thing! Will let you know if i face any difficulties!

**Comment by GemmaTuron** [comment]
Hi @masroor07 !

great, please also test that actually doing predictions works, and paste the outputs in the issue of that model, as well as testing the google colab implementation.
I've also assigned this model to another intern, Zakhia, if she finds issues please try to work together. In our pipeline, each new model incorporated is tested by at least two different people

**Comment by masroor07** [comment]
> Hi @masroor07 !
> 
> great, please also test that actually doing predictions works, and paste the outputs in the issue of that model, as well as testing the google colab implementation. I've also assigned this model to another intern, Zakhia, if she finds issues please try to work together. In our pipeline, each new model incorporated is tested by at least two different people

Alright! Will go through the model and try doing some prediction work. 
Thank you for the review

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron,
I fetch and serve model eos1bba successfully on CLI as well as on Colab. But it gave me an error when i execute "run" api after sometime. Same error occurred both on CLI and Colab, The error is "TypeError: 'NoneType' object is not subscriptable". I'm attaching the log file here,
[eos1bba_log.log](https://github.com/ersilia-os/ersilia/files/10938913/eos1bba_log.log)

@masroor07, did your run api executed successfully??

@carcablop any idea, how to resolve this??

Thanks.

**Comment by karthikjetty** [comment]
Hi @ZakiaYahya. Can you try running it again? I was making some small changes to the model and realized I accidentally pushed some code I was using for debugging. Let me know what happens.

**Comment by ZakiaYahya** [comment]
> Hi @ZakiaYahya. Can you try running it again in about an hour? I was making some small changes to the model and realized I accidentally pushed some code I was using for debugging. Let me know what happens.

Okay, @karthikjetty once you done just let me know.
Thanks.

**Comment by masroor07** [comment]
> Hi @ZakiaYahya. Can you try running it again in about an hour? I was making some small changes to the model and realized I accidentally pushed some code I was using for debugging. Let me know what happens.

Hi @karthikjetty 
Any update ?

**Comment by karthikjetty** [comment]
Hi @masroor07 @ZakiaYahya!
Thank you for testing the model! I'm still debugging what's going on! Thank you guys for being proactive. I'll let you guys know when it's ready to test again.

**Comment by ZakiaYahya** [comment]
> Hi @masroor07 @ZakiaYahya! Thank you for testing the model! I'm still debugging what's going on! Thank you guys for being proactive. I'll let you guys know when it's ready to test a

> Hi @masroor07 @ZakiaYahya! Thank you for testing the model! I'm still debugging what's going on! Thank you guys for being proactive. I'll let you guys know when it's ready to test again.

Hello @karthikjetty thanks for letting us know. Once you done with debugging, kindly let us know.
Thanks.

**Comment by masroor07** [comment]
> Hi @masroor07 @ZakiaYahya! Thank you for testing the model! I'm still debugging what's going on! Thank you guys for being proactive. I'll let you guys know when it's ready to test again.

Alright! Thank you for the update

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya and @masroor07 ,

Thanks for the tests. I'm following up the conversation with @karthikjetty on the specific model [issue](https://github.com/ersilia-os/eos1bba/issues/4). It does look like the conversion of the model to output is not well defined.

**Comment by ZakiaYahya** [comment]
> Hi @ZakiaYahya and @masroor07 ,
> 
> Thanks for the tests. I'm following up the conversation with @karthikjetty on the specific model [issue](https://github.com/ersilia-os/eos1bba/issues/4). It does look like the conversion of the model to output is not well defined.

Alright @GemmaTuron. Yes, it seems like model is having a problem during output conversion as fetch, serve and run api's are working perfectly fine.

**Comment by masroor07** [comment]
> Hi @ZakiaYahya and @masroor07 ,
> 
> Thanks for the tests. I'm following up the conversation with @karthikjetty on the specific model [issue](https://github.com/ersilia-os/eos1bba/issues/4). It does look like the conversion of the model to output is not well defined.

Alright! will try to keep up with the updates and try testing the model once the necessary changes are made.

**Comment by masroor07** [comment]
**SELECTED MODEL:**  [SMILES TO IUPAC](https://github.com/Kohulan/Smiles-TO-iUpac-Translator)
After exploring all the models that were for **WEEK 2: TASK 1**, I have selected this model to work on. From day one of we have been working with SMILES (one of the many ways that is used to represent and name compounds). The reason why I chose this model is because it is core to a number of possible researches in the areas involving designing and synthesizing  of new chemical compounds. After going through a few online resources, I could understand that a model like this helps save significant amounts of time and effort in various drug discovery projects. Understanding the application of a model like this can help me have an overall better understanding of things. Also, it will open me to exploring more about Neural networks and other concepts of Machine learning and Deep learning. I will also get to analyze data (chemical data), and improve my data analysis skills. I am also interested in having a better understanding of the implementation of things and this can prove crucial. With the wide number of applications, it is a good way to understand its various use cases in various domains.

**Comment by masroor07** [comment]
Can i work 

> **SELECTED MODEL:** [SMILES TO IUPAC](https://github.com/Kohulan/Smiles-TO-iUpac-Translator) After exploring all the models that were for **WEEK 2: TASK 1**, I have selected this model to work on. From day one of we have been working with SMILES (one of the many ways that is used to represent and name compounds). The reason why I chose this model is because it is core to a number of possible researches in the areas involving designing and synthesizing of new chemical compounds. After going through a few online resources, I could understand that a model like this helps save significant amounts of time and effort in various drug discovery projects. Understanding the application of a model like this can help me have an overall better understanding of things. Also, it will open me to exploring more about Neural networks and other concepts of Machine learning and Deep learning. I will also get to analyze data (chemical data), and improve my data analysis skills. I am also interested in having a better understanding of the implementation of things and this can prove crucial. With the wide number of applications, it is a good way to understand its various use cases in various domains.

Hi @GemmaTuron,

Can I work on this model for Week 2?

**Comment by masroor07** [comment]
**Model Testing for: STOUT (SMILES to IUPAC)**

Link to Github repository: `https://github.com/Kohulan/Smiles-TO-iUpac-Translator`

I cloned the repositories and installed all the dependencies for the model.  After setting up the conda environment to run and test the model, I tried running the model using the sample code provied on the projects repository. It threw this error `"JVM DLL not found"`. I generated a log file to debug the probelm:

[Testing.txt](https://github.com/ersilia-os/ersilia/files/10958539/Testing.txt)

From the log file, it was quite obvious that the model needed JDK to be installed on the system. I had JDK installed on my windows, but not on my WSL. I installed JDK on my subsystem (UBUNTU), and was able to run the model.

I tried to run prediction for a few smiles and was able to get the desired output.  

**Output:**

[smile-iupac.csv](https://github.com/ersilia-os/ersilia/files/10958741/smile-iupac.csv)

**Comment by masroor07** [comment]
#### EML PREDICTIONS FOR STOUT MODEL
* I was able to run predictions for the EML file for the STOUT model. 
* Created a simple `.py` and imported the method `translate_forward`cto convert SMILES to IUPAC. Also, to covert IUPAC to SMILES, STOUT has a method called `translate_reverse` 
* Fetched the csv and converted it into a pandas dataframe to make it easy (`eml_df = pd.read_csv('./eml_canonical.csv')`). 
* Used the models `translate_forward` method to convert the smiles present in the eml file to their respective IUPAC standard names.
* I performed predictions on the first five SMILES from the EML(considering that the dataset was large).
* I tried running the predictions for the `can_smiles` column as well. Turns out, the model can process them as well and give their IUPAC standard names.
* I stored the output into a csv.
**PREDICTION RESULTS:**
[results.csv](https://github.com/ersilia-os/ersilia/files/10960115/results.csv)

**Comment by GemmaTuron** [comment]
> #### EML PREDICTIONS FOR STOUT MODEL
> * I was able to run predictions for the EML file for the STOUT model.
> * Created a simple `.py` and imported the method `translate_forward`cto convert SMILES to IUPAC. Also, to covert IUPAC to SMILES, STOUT has a method called `translate_reverse`
> * Fetched the csv and converted it into a pandas dataframe to make it easy (`eml_df = pd.read_csv('./eml_canonical.csv')`).
> * Used the models `translate_forward` method to convert the smiles present in the eml file to their respective IUPAC standard names.
> * I performed predictions on the first five SMILES from the EML(considering that the dataset was large).
> * I tried running the predictions for the `can_smiles` column as well. Turns out, the model can process them as well and give their IUPAC standard names.
> * I stored the output into a csv.
>   **PREDICTION RESULTS:**
>   [results.csv](https://github.com/ersilia-os/ersilia/files/10960115/results.csv)

Hi @masroor07 ,

Great start! Can you read a bit about what exactly are SMILES and why the canonical smiles can be read as well? What would be best to use generally?

**Comment by GemmaTuron** [comment]
Hello @masroor07 !
Great explanations, thanks for your dedication. As an extra task for this week, might I ask you to try to run the ADME-NCATS models? We have had some issues with @pauline-banye with some of them and I'd like to know if these are persistent across users. Could you:

- Follow the installation detailed in the adme-ncats repo (please, use the development branch, not main)
- Downlowad the pretrained model PAMPA5 
- Test 5 molecules on the ADME-NCATS model as well as on the model implemented in Ersilia (eos81ew) and compare the results

**Comment by masroor07** [comment]
> Hello @masroor07 ! Great explanations, thanks for your dedication. As an extra task for this week, might I ask you to try to run the ADME-NCATS models? We have had some issues with @pauline-banye with some of them and I'd like to know if these are persistent across users. Could you:
> 
> * Follow the installation detailed in the adme-ncats repo (please, use the development branch, not main)
> * Downlowad the pretrained model PAMPA5
> * Test 5 molecules on the ADME-NCATS model as well as on the model implemented in Ersilia (eos81ew) and compare the results

Alright! Will get onto it as soon as possible

Thank you

**Comment by GemmaTuron** [comment]
Hi @masroor07 

Which is the command you are using that gets stuck? The models must be downloaded manually btw

**Comment by masroor07** [comment]
> Hi @pauline-banye, How long does it take to create the environment for the ADME-NCATS model? Seems like it takes a lot of time. Sorry for the inconvenience!
> 
> Thank you



> Hi @masroor07
> 
> Which is the command you are using that gets stuck? The models must be downloaded manually btw

It finally completed downloading all the the dependencies but `app.py` didn't seem to work! I received following error `ImportError: cannot import name 'escape' from 'jinja2'`. I simply uninstalled Flask and reinstalled Flask to solve the problem.
I am now downloading the models for testing.

Thank you

**Comment by karthikjetty** [comment]
Hi @masroor07 and @ZakiaYahya. Try testing the model now and seeing if you get any errors. Thanks for the catch.

**Comment by ZakiaYahya** [comment]
Hello @karthikjetty, Thanks for letting us know. I'll try it and will let you know as soon as possible. Thanks.

**Comment by ZakiaYahya** [comment]
> Hi @masroor07 and @ZakiaYahya. Try testing the model now and seeing if you get any errors. Thanks for the catch.

Hello @GemmaTuron AND @karthikjetty, the model is working fine now, you can check the output [here](https://github.com/ersilia-os/eos1bba/issues/4#issuecomment-1469179217)

**Comment by masroor07** [comment]
> Hi @masroor07 and @ZakiaYahya. Try testing the model now and seeing if you get any errors. Thanks for the catch.

Alright!

> > Hi @masroor07 and @ZakiaYahya. Try testing the model now and seeing if you get any errors. Thanks for the catch.
> 
> Hello @GemmaTuron AND @karthikjetty, the model is working fine now, you can check the output [here](https://github.com/ersilia-os/eos1bba/issues/4#issuecomment-1469179217)

Great! I will try running some predictions as well.

**Comment by masroor07** [comment]
> > Hi @pauline-banye, How long does it take to create the environment for the ADME-NCATS model? Seems like it takes a lot of time. Sorry for the inconvenience!
> > Thank you
> 
> > Hi @masroor07
> > Which is the command you are using that gets stuck? The models must be downloaded manually btw
> 
> It finally completed downloading all the the dependencies but `app.py` didn't seem to work! I received following error `ImportError: cannot import name 'escape' from 'jinja2'`. I simply uninstalled Flask and reinstalled Flask to solve the problem. I am now downloading the models for testing.
> 
> Thank you

I was able to run the model `PAMPA Permeability (pH 5.0)`.  I was able to follow the simple instructions to install the model on my sub system(UBUNTU). 

**MODEL INTERPRETATION:** The model provides predicted class (1 or 0) for a given compound. If the predicted class is '1', it means the compound is predicted to have 'low permeability' (i.e., log Peff < 1.0) and if the predicted class is '0', the compound is predicted to have 'moderate to high permeability' (i.e., log Peff > 1.0). The models also provide a probability score (between 0 and 1), shown in parentheses next to the predicted class.


**Input to the model:** I used 10 SMILES to test the model. 
[10_SMILES.csv](https://github.com/ersilia-os/ersilia/files/10975324/10_SMILES.csv)
**Output:**
[ADME_Predictions_2023-03-15-070819.csv](https://github.com/ersilia-os/ersilia/files/10975326/ADME_Predictions_2023-03-15-070819.csv)

I will now try to compare the results of the ADME-NCATS model with model implemented in Ersilia (eos81ew).

**Comment by GemmaTuron** [comment]
Perfect many thanks @masroor07 !
We need to check we are getting the same values from the original model and the one we implemented at Ersilia.
Please note we did some transformation in the Ersilia Model Hub to the results to give always the probability of 1, let's see if all is correctly working :)

**Comment by masroor07** [comment]
> 

Alright! thank you for the update.
I will compare the results in a while.

**Comment by pauline-banye** [comment]
Great job on debugging @masroor07 😊. Glad you were able to get the NCATS ADME model working 👍

**Comment by ZakiaYahya** [comment]
> > Great job on debugging @masroor07 😊. Glad you were able to get the NCATS ADME model working 👍
> > Thanks @pauline-banye !
> 
> I have been trying to fetch PAMPA5 using ersilia. But i get the following error:
> 
> ```
> mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '../../checkpoints'
> ```
> 
> I tried giving elevated privileges to the user but that doesn't seem to solve the problem.

@masroor07, i'm getting the same error while fetching ersilia NCAT solubility model. If you find how to resolve it, let me know too. Thanks

**Comment by masroor07** [comment]
> 

Still facing the same issue. Tried giving the user privileges but that doesn't seem to solve my problem.

**Comment by GemmaTuron** [comment]
Hi @masroor07 and @ZakiaYahya 

Are your users Admins of the computers you are using?
@pauline-banye can you share more information on where the mkdir command is used? perhaps it wouldn't be necessary

**Comment by pauline-banye** [comment]
> Hi @masroor07 and @ZakiaYahya
> 
> Are your users Admins of the computers you are using? You need to grant yourselves super-user privileges (this differs in windows, linux and macos). In Linux you can check [this](https://linuxopsys.com/topics/give-normal-user-root-privileges) for example. As a workaround @masroor07 can you use the Colab implementation to run the model through Ersilia? @pauline-banye can you share more information on where the mkdir command is used? perhaps it wouldn't be necessary

Hi @GemmaTuron, the creation of the directory is not necessary anymore. 

It was necessary when the models were downloaded directly. It checks if the directory exists and creates it if it doesn't. 

The current setup with the models already downloaded and within the repository makes it unnecessary.

**Comment by GemmaTuron** [comment]
@pauline-banye then this should be removed from the code, legacy code specially if it requires special user permissions can give problems afterwards as we are seeing

**Comment by ZakiaYahya** [comment]
> Hi @masroor07 and @ZakiaYahya
> 
> Are your users Admins of the computers you are using? You need to grant yourselves super-user privileges (this differs in windows, linux and macos). In Linux you can check [this](https://linuxopsys.com/topics/give-normal-user-root-privileges) for example. As a workaround @masroor07 can you use the Colab implementation to run the model through Ersilia? @pauline-banye can you share more information on where the mkdir command is used? perhaps it wouldn't be necessary

Hello @GemmaTuron and @pauline-banye, i have successfully fetch the model by granting user privileges.
Thanks.

**Comment by pauline-banye** [comment]
> > Hi @masroor07 and @ZakiaYahya
> > 
> > Are your users Admins of the computers you are using? You need to grant yourselves super-user privileges (this differs in windows, linux and macos). In Linux you can check [this](https://linuxopsys.com/topics/give-normal-user-root-privileges) for example. As a workaround @masroor07 can you use the Colab implementation to run the model through Ersilia? @pauline-banye can you share more information on where the mkdir command is used? perhaps it wouldn't be necessary
> 
> Hello @GemmaTuron and @pauline-banye, i have successfully fetch the model by granting user privileges.
> Thanks.

That's fantastic @ZakiaYahya  👍

**Comment by masroor07** [comment]
> Hi @masroor07 and @ZakiaYahya
> 
> Are your users Admins of the computers you are using? You need to grant yourselves super-user privileges (this differs in windows, linux and macos). In Linux you can check [this](https://linuxopsys.com/topics/give-normal-user-root-privileges) for example. As a workaround @masroor07 can you use the Colab implementation to run the model through Ersilia? @pauline-banye can you share more information on where the mkdir command is used? perhaps it wouldn't be necessary


Will try running the model using colab alright! I probably messed up with granting privileges, will try to work my way around it.

Thank you

**Comment by masroor07** [comment]
Was finally able to fetch the model.
```
Fetching eos81ew done in time: 0:03:38.524597s
18:56:29 | INFO     | Fetching eos81ew done successfully: 0:03:38.524597
```

Tried running it for a sample smile:
```
 ersilia api run -i "CCCC"
{
    "input": {
        "key": "IJDNQMDRQITEOD-UHFFFAOYSA-N",
        "input": "CCCC",
        "text": "CCCC"
    },
    "output": {
        "outcome": [
            1.970733478628972e-07
        ]
    }
}
```

**Comment by masroor07** [comment]
> Hello @masroor07 ! Great explanations, thanks for your dedication. As an extra task for this week, might I ask you to try to run the ADME-NCATS models? We have had some issues with @pauline-banye with some of them and I'd like to know if these are persistent across users. Could you:
> 
> * Follow the installation detailed in the adme-ncats repo (please, use the development branch, not main)
> * Downlowad the pretrained model PAMPA5
> * Test 5 molecules on the ADME-NCATS model as well as on the model implemented in Ersilia (eos81ew) and compare the results

**Comparison - ADME-NCATS(PAMPA5.0) AND NCATS-PAMPA5(eos81ew)**
Summary of the overall process.
**adme-ncats(PAMPA5.0):** The model provides predicted class (1 or 0) for a given compound. If the predicted class is '1', it means the compound is predicted to have 'low permeability' (i.e., log Peff < 1.0) and if the predicted class is '0', the compound is predicted to have 'moderate to high permeability' (i.e., log Peff > 1.0). The models also provide a probability score (between 0 and 1), shown in parentheses next to the predicted class.

Input to the model:
[10_SMILES.csv](https://github.com/ersilia-os/ersilia/files/10975324/10_SMILES.csv)
Output:
[ADME_Predictions_2023-03-15-070819.csv](https://github.com/ersilia-os/ersilia/files/10975326/ADME_Predictions_2023-03-15-070819.csv)
**ncats-pampa5(eos81ew):** Vitro surrogate to determine the permeability of drugs across cellular membranes. The Peff was converted to logarithmic, log Peff value lower than 2.0 were considered to have low to moderate permeability, and those with a value higher than 2.5 were considered as high-permeability compounds. Compounds with a value between 2.0 and 2.5 were omitted from the dataset.

**Challenges during installation:** The model requires the user to have elevated privileges which should not be the case. I was able to solve the problem by elevating the user's privileges and during the process, ended up corrupting a couple of my system files. I was able to resolve the issue by going through a discussion on stackoverflow. The error that was thrown: `mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '../../checkpoints'`

**Input to the model:** 
[10_SMILES.csv](https://github.com/ersilia-os/ersilia/files/10975324/10_SMILES.csv)

**Output:**
[processed.csv](https://github.com/ersilia-os/ersilia/files/10993809/processed.csv)

**Comment by GemmaTuron** [comment]
Hi @masroor07 

Great that you were able to run both models! The ADME NCATS and the implementation at Ersilia are the same model, so in the eos81ew you are simply describing the dataset used to train the model, but not the actual model output? Can you now compare the predictions you got for the same molecules on both models and see if they make sense? Since they are the same model they should be coinciding

**Comment by pauline-banye** [comment]
> @pauline-banye then this should be removed from the code, legacy code specially if it requires special user permissions can give problems afterwards as we are seeing

Hi @GemmaTuron I can make the edits to the code right now. I'm creating a temporary fork and making a PR.

**Comment by masroor07** [comment]
> Hi @masroor07
> 
> Great that you were able to run both models! The ADME NCATS and the implementation at Ersilia are the same model, so in the eos81ew you are simply describing the dataset used to train the model, but not the actual model output? Can you now compare the predictions you got for the same molecules on both models and see if they make sense? Since they are the same model they should be coinciding

Alright, will try to run predictions for same molecules on both the model.

**Comment by masroor07** [comment]
> Hi @masroor07
> 
> Great that you were able to run both models! The ADME NCATS and the implementation at Ersilia are the same model, so in the eos81ew you are simply describing the dataset used to train the model, but not the actual model output? Can you now compare the predictions you got for the same molecules on both models and see if they make sense? Since they are the same model they should be coinciding

Hi @GemmaTuron,

* I tried running the predictions for various molecules on both the models. And yes, the outputs coincide. In eos81w, a probability of below 0.5 is considered highly permeable where as a probability of 0.5 or greater is considered low permeability. For example, If I run a prediction for the SMILE input `Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1`, the output I get is **0.903985857963562**, which indicates that the molecule is not highly permeable. 
* But, for the SMILE input `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`, the output is **0.0090377377346158**, which indicates that the molecule is moderate to highly permable.
* And when i try running the predictions for the same molecules on ADME NCATS model,   `Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1`, the output I get is **low permeability** with **Predicted Class (Probability) equal to 1** and for  `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`, the output is **high permeability** with **Predicted Class (Probability) equal to 0**

**Comment by GemmaTuron** [comment]
> > Hi @masroor07
> > Great that you were able to run both models! The ADME NCATS and the implementation at Ersilia are the same model, so in the eos81ew you are simply describing the dataset used to train the model, but not the actual model output? Can you now compare the predictions you got for the same molecules on both models and see if they make sense? Since they are the same model they should be coinciding
> 
> Hi @GemmaTuron,
> 
> * I tried running the predictions for various molecules on both the models. And yes, the outputs coincide. In eos81w, a probability of below 0.5 is considered highly permeable where as a probability of 0.5 or greater is considered low permeability. For example, If I run a prediction for the SMILE input `Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1`, the output I get is **0.903985857963562**, which indicates that the molecule is not highly permeable.
> * But, for the SMILE input `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`, the output is **0.0090377377346158**, which indicates that the molecule is moderate to highly permable.
> * And when i try running the predictions for the same molecules on ADME NCATS model,   `Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1`, the output I get is **low permeability** with **Predicted Class (Probability) equal to 1** and for  `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`, the output is **high permeability** with **Predicted Class (Probability) equal to 0**

This is a great explanation thanks @masroor07 !

**Comment by masroor07** [comment]
> > > Hi @masroor07
> > > Great that you were able to run both models! The ADME NCATS and the implementation at Ersilia are the same model, so in the eos81ew you are simply describing the dataset used to train the model, but not the actual model output? Can you now compare the predictions you got for the same molecules on both models and see if they make sense? Since they are the same model they should be coinciding
> > 
> > 
> > Hi @GemmaTuron,
> > 
> > * I tried running the predictions for various molecules on both the models. And yes, the outputs coincide. In eos81w, a probability of below 0.5 is considered highly permeable where as a probability of 0.5 or greater is considered low permeability. For example, If I run a prediction for the SMILE input `Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1`, the output I get is **0.903985857963562**, which indicates that the molecule is not highly permeable.
> > * But, for the SMILE input `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`, the output is **0.0090377377346158**, which indicates that the molecule is moderate to highly permable.
> > * And when i try running the predictions for the same molecules on ADME NCATS model,   `Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1`, the output I get is **low permeability** with **Predicted Class (Probability) equal to 1** and for  `CCCSc1ccc2nc(NC(=O)OC)[nH]c2c1`, the output is **high permeability** with **Predicted Class (Probability) equal to 0**
> 
> This is a great explanation thanks @masroor07 !

Thank you for the review!

**Comment by masroor07** [comment]
### Model: 
OptiMol: Optimization of binding affinities in chemical space for drug discovery

### Description:
An optimization pipeline that leverages complementary structure-based and ligand-based methods. The model introduces new Graph to SELFIES VAE. The model iteratively selects promising compounds in the chemical space using a ligand-centered generative model and then performs the molecular docking  to guide compound optimization. 

### Slug: 
**optimol**

### Publication:
https://www.biorxiv.org/content/10.1101/2020.05.23.112201v2.full#F1
### Github Repository:
https://www.biorxiv.org/content/10.1101/2020.05.23.112201v2.full#F1

### Summary
OptiMol model is implemented in `Pytorch` and `DGL`. The model was trained for 50 epochs using Adam optimizer. It proposes the optimization of the current state of art methods that do not leverage the structure of a target.  A new VAE that is more computationally efficient while retaining state of the art results is introduced. Instead of performing docking on a fixed drug bank, promising compounds in the whole chemical space using a ligand-centered generative model are selected and molecular docking is then used as an oracle to guide compound optimization, allowing iterative generation of leads that betters fit the target structure. This oracle is costly and Bayesian optimization with recently published method : Conditioning by Adaptive Sampling was used to optimize the whole approach.

To generate compounds with high binding affinities, we could  use one of the three binding affinity estimates:
* Experimental bio-assays
* Quantitative Structure Activity Relationship (QSAR)
* Molecular docking softwares
There methods can give good results but can be inaccurate. Optimol byepasses these limitations by resorting to a docking program, that uses physics-based molecular mechanics force fields to compute binding affinities.

**Comment by GemmaTuron** [comment]
Hi @masroor07 !

Thanks for the detailed explanation, this model looks very relevant to some projects we are working at in Ersilia! LEt me give you a few extra pointers:

- It is best to always cite the peer reviewed publication instead of the preprint, if available. In this case, it is published in Journal of Chemical Information and Modeling
- The code link should bring us to the GitHub link, but it is the biorxiv still
- Some extra information from the code, for example, which license it uses, would be good to have

**Comment by masroor07** [comment]
> Hi @masroor07 !
> 
> Thanks for the detailed explanation, this model looks very relevant to some projects we are working at in Ersilia! LEt me give you a few extra pointers:
> 
> * It is best to always cite the peer reviewed publication instead of the preprint, if available. In this case, it is published in Journal of Chemical Information and Modeling
> * The code link should bring us to the GitHub link, but it is the biorxiv still
> * Some extra information from the code, for example, which license it uses, would be good to have

Thank you for the positive review and the extra pointers. 
* Updated the link to the publication on Journal of Chemical Information and Modeling
* Seems like i had pasted the same link. Changed it to the Github repository.
* Noted the third pointer as well!

**Comment by GemmaTuron** [comment]
Hi @masroor07 !

While you look for further models, can I ask you to include this model suggestion in our [list](https://airtable.com/shroQLlkcmDcC0xzm)?

Thanks!

**Comment by masroor07** [comment]
### Model:
**MolGAN: An implicit generative model for small molecular graphs**

### Description:
A free generative model that that provides a way around the expensive graph matching procedures. The model adapts generative adversarial networks which is backed by RL to generate chemical molecules with desired properties. 

### Slug:
**molgan**

### Publication:
https://arxiv.org/abs/1805.11973 (PDF)

### Github Repository:
https://github.com/nicola-decao/MolGAN

### Summary:
MolGAN is an implicit generative model for molecular graphs of small size which can be jointly trained with a GAN and a RL objective to generate molecular graphs with higher validity and novelty. It can achieve better chemical property scores and also removes the additional overhead when compared to the SMILES (which are generated from a graph based representation of molecules) based sequential GAN model for molecular generation. The model consists of three main components: generator, discriminator and a reward network. 
* The generator takes a sample and generates an annotated graph representation of a molecule.
* The discriminator compares the the samples from dataset and generator and assigns scores to them.
* The reward network is used to approximate the reward function. It also optimizes molecule generation.
**Dataset:** The model is trained using QM9 dataset  (a subset of GDB-17 chemical database)
### LICENSE:
MIT

**Comment by GemmaTuron** [comment]
Hi @masroor07 !

Thanks, good model and very detailed description, I appreciate it! My only concern is that is a bit old  (runs in Py3.6) let's hope it can be easily bumped to py 3.10!)
Can you add it to the model list while you look for a third model suggestion?

**Comment by masroor07** [comment]
> Hi @masroor07 !
> 
> Thanks, good model and very detailed description, I appreciate it! My only concern is that is a bit old (runs in Py3.6) let's hope it can be easily bumped to py 3.10!) Can you add it to the model list while you look for a third model suggestion?

@GemmaTuron, 
Thank you for the positives! I did notice the python version but I guess there must be a way to make the required changes/updates to the code.
Yes, sure! I will add it to the model list.

**Comment by masroor07** [comment]
> hile you look
@GemmaTuron 
To add the model to the list, I had to fill the form right?

**Comment by GemmaTuron** [comment]
yes please: https://airtable.com/shroQLlkcmDcC0xzm

**Comment by masroor07** [comment]
> yes please: https://airtable.com/shroQLlkcmDcC0xzm

I filled the form! Thank you

**Comment by masroor07** [comment]
### Model 3:
**EpitopeVec: Linear Epitope Prediction Using Deep Protein Sequence Embeddings**

### Description:
EpitopeVec is model to predict the linear-B Peptides. It uses a combination of residue properties, modified antigenicity scales, and protein language model-based representations (protein vectors) as features of peptides for linear BCE predictions.

###Slug:
**epitopevec**
###Publication:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8652027/

### Github Repository:
https://github.com/hzi-bifo/epitope-prediction

### Summary:
The region of an antigen recognized by antibodies is known as an epitope and if it is a continuous stretch of  amino acids, it is a linear epitope. The  identification of BCEs is important in many applications. 
EpitopeVec predicts the linear B-cell epitopes. It is a tool that combines commonly used propensity scales, residue features and modified antigenicity scales for vector representation of the peptides. It is based on a SVM model trained on a large set of experimentally verified epitopes and makes use of different amino acid features. 

**Datasets:** EpitopeVec is trained on various small and large datasets derived from Bcipep and Immune Epitope Database (IEDB)
* It takes protein sequences as input
* Returns the list of peptides that can be epitopes.
### License:
GPLv3

**Comment by masroor07** [comment]
Hi @GemmaTuron, 
I was tring to reinstall NCATS-ADME on my system. I am facing a pickling issue i.e. `_pickle.UnpicklingError: invalid load key, '<'.'.

**Comment by masroor07** [comment]
> Hi @GemmaTuron, I was tring to reinstall NCATS-ADME on my system. I am facing a pickling issue i.e. `_pickle.UnpicklingError: invalid load key, '<'.'.

I was able to understand why a number of people face the pickling issue. The reason is simple: They had clonen the master branch of NCATS-ADME, which has outdated links and also, the code is not up to date. I cloned the "development" branch and that solved my issue. I just had to reinstall flask to solve the `jinja2` issue.

**Comment by masroor07** [comment]
#### Update: 
I tried running the NCATS-HLM model. The model doesn't accept the input. I tried passing a csv to it. I also tried passing a text file to it but it doesn't process either of the input formats. The error message:
**There was an error processing your file. Please make sure you have selected a file that contains SMILES, indicate if the file contains a header and the column number containing the SMILES.**
Input csv file: 
[10_SMILES.csv](https://github.com/ersilia-os/ersilia/files/11071542/10_SMILES.csv)
I tried passing the same input file to PAMPA5 and and PAMPA7.4 as well. And they both were able to process the input file.

**Comment by masroor07** [comment]
> #### Update:
> I tried running the NCATS-HLM model. The model doesn't accept the input. I tried passing a csv to it. I also tried passing a text file to it but it doesn't process either of the input formats. The error message: **There was an error processing your file. Please make sure you have selected a file that contains SMILES, indicate if the file contains a header and the column number containing the SMILES.** Input csv file: [10_SMILES.csv](https://github.com/ersilia-os/ersilia/files/11071542/10_SMILES.csv) I tried passing the same input file to PAMPA5 and and PAMPA7.4 as well. And they both were able to process the input file.

I tried running the deployed [HLM model](https://opendata.ncats.nih.gov/adme/predictions) which processes the input file. Here is the outputfile of the predictions ran using it: 
[ADME_Predictions_2023-03-26-183023.csv](https://github.com/ersilia-os/ersilia/files/11071644/ADME_Predictions_2023-03-26-183023.csv)

**Comment by masroor07** [comment]
**UPDATE:**
* **PAMPA 5 AND PAMPA 7.4:** I tried running predictions using both and no, PAMPA 5 doesn't show `PAMPA50` as the model rather it shows **PAMPA** as the model. We can also observe a more precise probability score than **PAMPA5** in the later version. I tried running the model on my local system and using the deployed version [HERE](https://opendata.ncats.nih.gov/adme/predictions) as well.

**Note:** The authors should change the model output to **PAMPA 7.4**. That would make it more clear to understand the model that we are using.(Right?) 

I ran tests for the first 10 smiles from the EML. 
**INPUT:**
[10_SMILES.csv](https://github.com/ersilia-os/ersilia/files/11072164/10_SMILES.csv)

**OUTPUT:**
* Local test: 
[ADME_Predictions_2023-03-26-212850.csv](https://github.com/ersilia-os/ersilia/files/11072169/ADME_Predictions_2023-03-26-212850.csv)

* Deployed model: 
[ADME_Predictions_2023-03-26-211505 (WEB).csv](https://github.com/ersilia-os/ersilia/files/11072175/ADME_Predictions_2023-03-26-211505.WEB.csv)

**Comment by GemmaTuron** [comment]
Hi @masroor07 !

That's great, so if I understand it correctly:

- HLM model works
- PAMPA5 works, with the results column stating PAMPA (only)
- PAMPA7.4 works, with the results column stating? (sorry missed that one!)

If you can confirm that, I think we could reopen [this issue](https://github.com/ersilia-os/ersilia/issues/584) and unarchive the model repo so that we can push the HLM model to the Hub as well. What do you think?

**Comment by masroor07** [comment]
> Hi @masroor07 !
> 
> That's great, so if I understand it correctly:
> 
> * HLM model works
> * PAMPA5 works, with the results column stating PAMPA (only)
> * PAMPA7.4 works, with the results column stating? (sorry missed that one!)
> 
> If you can confirm that, I think we could reopen [this issue](https://github.com/ersilia-os/ersilia/issues/584) and unarchive the model repo so that we can push the HLM model to the Hub as well. What do you think?

The HLM model that has been deployed to [opendata](https://opendata.ncats.nih.gov/adme/) works, yes.
* No, PAMPA 7.4 works, shows PAMPA
* PAMPA5 works, shows PAMPA50

**Comment by GemmaTuron** [comment]
I've reopened the issues to tackle them:
- HLM incorporation: the issue is reopened - I suggest creating a new repo, and copying the code from another of the NCATS models but changing the model checkpoints for the appropriate ones?
- PAMPA7.4: once HLM is working if there is time we can add the model as well

**Comment by masroor07** [comment]
**Submitted my final application**
Hello @GemmaTuron, Thank you for all the help during the contribution period! Got learn a ton of thing. A thank you to other contributors for all the help during the contribution phase. Look forward to keep contributing to **Ersilia!**
